apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.admin.user | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.admin.password | quote }}
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL_HOST
              value: {{ .Values.keycloak.database.host | quote }}
            - name: KC_DB_DATABASE
              value: {{ .Values.keycloak.database.database | quote }}
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloak.database.username | quote }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.keycloak.database.password | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
