# Keycloak Secrets
# Contains sensitive credentials for Keycloak admin and database
# SECURITY WARNING: Never commit passwords to Git!
# Best practices:
#   1. Use --set flags during helm install
#   2. Use external secret management (e.g., Sealed Secrets, External Secrets Operator)
#   3. Use existing secrets via .Values.keycloak.admin.existingSecret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Admin credentials - required for initial setup
  admin-username: {{ .Values.keycloak.admin.username | quote }}
  admin-password: {{ required "A valid .Values.keycloak.admin.password is required!" .Values.keycloak.admin.password | quote }}
  # Database password - only created if not using existing secret or embedded PostgreSQL
  {{- if not .Values.keycloak.database.existingSecret }}
  {{- if not .Values.postgresql.enabled }}
  db-password: {{ required "A valid .Values.keycloak.database.password is required!" .Values.keycloak.database.password | quote }}
  {{- end }}
  {{- end }}
