{{- if .Values.configMap.enabled -}}
# ConfigMap for custom Keycloak configuration
# Use this to provide custom themes, providers, or realm configurations
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-config
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}