# Keycloak Deployment
# This deployment manages the Keycloak application pods
# Keycloak.X (Quarkus-based) is used for better performance and cloud-native features
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
# Replica count - managed by HPA if autoscaling is enabled
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
# Trigger pod restart when secrets change
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
# Use dedicated service account for RBAC
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}
# Pod-level security context (applies to all containers)
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
# Optional init containers for custom setup (e.g., theme installation)
      {{- with .Values.keycloak.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: keycloak
        # Container-level security context (non-root, no privilege escalation)
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          # Keycloak.X (Quarkus-based) image from official registry
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - /opt/keycloak/bin/kc.sh
        args:
        # NOTE: Change to 'start' for production (requires TLS configuration)
          - start-dev
          # Environment variables for Keycloak configuration
        env:
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: {{ include "keycloak.fullname" . }}
              key: admin-username
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              {{- if .Values.keycloak.admin.existingSecret }}
              name: {{ .Values.keycloak.admin.existingSecret }}
              key: {{ .Values.keycloak.admin.existingSecretKey }}
              {{- else }}
              name: {{ include "keycloak.fullname" . }}
              key: admin-password
              {{- end }}
        - name: KC_DB
          value: {{ .Values.keycloak.database.vendor | quote }}
        - name: KC_DB_URL_HOST
          value: {{ include "keycloak.dbHost" . | quote }}
        - name: KC_DB_URL_PORT
          value: {{ include "keycloak.dbPort" . | quote }}
        - name: KC_DB_URL_DATABASE
          value: {{ include "keycloak.dbName" . | quote }}
        - name: KC_DB_USERNAME
          value: {{ include "keycloak.dbUsername" . | quote }}
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              {{- if .Values.keycloak.database.existingSecret }}
              name: {{ .Values.keycloak.database.existingSecret }}
              key: {{ .Values.keycloak.database.existingSecretKey }}
              {{- else if .Values.postgresql.enabled }}
              name: {{ .Release.Name }}-postgresql
              key: password
              {{- else }}
              name: {{ include "keycloak.fullname" . }}
              key: db-password
              {{- end }}
        - name: KC_PROXY
          value: {{ .Values.keycloak.proxy | quote }}
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HEALTH_ENABLED
          value: {{ .Values.keycloak.health.enabled | quote }}
        - name: KC_METRICS_ENABLED
          value: {{ .Values.keycloak.metrics.enabled | quote }}
        - name: jgroups.dns.query
          value: {{ printf "%s-headless" (include "keycloak.fullname" .) }}
        {{- with .Values.keycloak.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.startupProbe }}
        startupProbe:
          {{- toYaml .Values.startupProbe | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
          {{- if .Values.configMap.enabled }}
          # Mount custom configuration from ConfigMap
          - name: config
            mountPath: {{ .Values.configMap.mountPath }}
            {{- if .Values.configMap.subPath }}
            subPath: {{ .Values.configMap.subPath }}
            {{- end }}
          {{- end }}
          {{- with .Values.keycloak.extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      volumes:
        {{- if .Values.configMap.enabled }}
        # ConfigMap volume for custom configuration
        - name: config
          configMap:
            name: {{ include "keycloak.fullname" . }}-config
        {{- end }}
        {{- with .Values.keycloak.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
