apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-dev
  namespace: argocd
  annotations:
    cascade.dev/refresh: "$(date +%s)"
spec:
  project: ${ARGOCD_PROJECT_NAME}
  source:
    repoURL: 'https://github.com/${GITHUB_USERNAME}/${GIT_REPO_NAME}.git'
    targetRevision: ${GIT_BRANCH_DEV}
    path: helm/keycloak
    helm:
      releaseName: keycloak-dev
      valueFiles:
        - values.yaml
      parameters:
        - name: keycloak.admin.password
          value: admin123
        # Enable the postgresql sub-chart
        - name: postgresql.enabled
          value: "true"
        - name: postgresql.auth.database
          value: keycloak_dev
        - name: postgresql.auth.username
          value: keycloak_dev
        # Point keycloak to the new database
        - name: keycloak.database.host
          value: keycloak-dev-postgresql
        - name: keycloak.database.database
          value: keycloak_dev
        - name: keycloak.database.username
          value: keycloak_dev
        - name: keycloak.database.existingSecret
          value: keycloak-dev-postgresql
        - name: keycloak.database.existingSecretKey
          value: postgresql-password
        # Force override of environment variables
        - name: keycloak.extraEnv[0].name
          value: KC_DB_URL_HOST
        - name: keycloak.extraEnv[0].value
          value: keycloak-dev-postgresql
        - name: keycloak.extraEnv[1].name
          value: KC_DB_DATABASE
        - name: keycloak.extraEnv[1].value
          value: keycloak_dev
        - name: keycloak.extraEnv[2].name
          value: KC_DB_USERNAME
        - name: keycloak.extraEnv[2].value
          value: keycloak_dev
        - name: keycloak.extraEnv[3].name
          value: KC_DB_PASSWORD
        - name: keycloak.extraEnv[3].valueFrom.secretKeyRef.name
          value: keycloak-dev-postgresql
        - name: keycloak.extraEnv[3].valueFrom.secretKeyRef.key
          value: postgresql-password
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
