apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-dev
  namespace: argocd
spec:
  # Replaced hardcoded project name with a variable
  project: ${ARGOCD_PROJECT_NAME}
  source:
    # Reconstructed repo URL using GITHUB_USERNAME and GIT_REPO_NAME
    repoURL: 'https://github.com/${GITHUB_USERNAME}/${GIT_REPO_NAME}.git'
    # Replaced hardcoded branch name with a variable
    targetRevision: ${GIT_BRANCH_DEV}
    path: keycloak-ops/helm/keycloak
    helm:
      releaseName: keycloak-dev
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
