apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-dev
  namespace: argocd
  annotations:
    cascade.dev/refresh: "force-sync-9"
spec:
  project: ${ARGOCD_PROJECT_NAME}
  source:
    repoURL: 'https://github.com/${GITHUB_USERNAME}/${GIT_REPO_NAME}.git'
    targetRevision: ${GIT_BRANCH_DEV}
    path: manifests/keycloak-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
