# WARNING: These are default test passwords for development/testing only
# For production, use the create-secrets.sh script or a secret management tool
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
type: Opaque
stringData:
  username: admin
  password: admin123  # CHANGE THIS FOR PRODUCTION!
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
type: Opaque
stringData:
  username: keycloak
  password: keycloak123  # MUST MATCH postgres-secret password below!
