apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak-dev

nameSuffix: -dev

bases:
  - ../../base

commonLabels:
  environment: dev

patches:
  - target:
      kind: Deployment
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Ingress
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: keycloak-dev.example.com
  - target:
      kind: Deployment
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: postgres-service-dev

configMapGenerator:
  - name: keycloak-env
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
